# Generated by Django 5.2.7 on 2025-10-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_disponibilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='hora_fin_m',
            field=models.TimeField(default='12:00', verbose_name='Fin mañana'),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='hora_fin_t',
            field=models.TimeField(default='18:00', verbose_name='Fin tarde'),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='hora_inicio_m',
            field=models.TimeField(default='08:00', verbose_name='Inicio mañana'),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='hora_inicio_t',
            field=models.TimeField(default='14:00', verbose_name='Inicio tarde'),
        ),
    ]
