# Generated by Django 5.2.7 on 2025-10-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_disponibilidad_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='hora_fin_m',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='hora_fin_t',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='hora_inicio_m',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='hora_inicio_t',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
