# Generated by Django 5.0.4 on 2025-11-26 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cita'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('empresa', 'fecha', 'hora_inicio', 'estado')},
        ),
    ]
